---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongodb-secret
  namespace: mongo
spec:
  encryptedData:
    mongo-root-password: AgBLfoXJAjD0ncLqztImhUegOTO6aOtQuB9o0H5/xf1MM7Vi72Anyj4UUMpQxdjzx+3plUbgbxVRBC7WzxO4BdfehMW2DRbxJEd83Aphce1mPKpP+YlDEZDloS7rn3TjH+wsi0qfRrnSnFW7M6FiXuzw1h44lA1XSDE7Lg1WLd+TXCOE+l1i0RsAsdxDgmwR8ridkxDRUHw3zO9OWCwFrK4wUqpqZwRl8bP9ZJIy8mme8RWzZ9wLftlVd57nMRZopLI0QWec1rn9J8bXuKAHWaXn9HZBRqIWZga2uNrRUFLIcA5bnjMIbkyD2U4v2nQKVK7l6KeKkYdqRyCjUo/KF5Hr1hAB8qceJnklvrFxOTgdJh8Ac1O140OKPKF1lExmAcrVxJyXThPLMpHKvDuRZQxFBZNNwDHXJ1/0YCe/rUU9hyjSq0Qwe2rM0PmJ6Pl9psBkos3WQ22NsjoJBu2L5vBAH8nv3OlBYNgsUfx4zSjQHScQ74b10GNN+Pm3PRfi2q5EAtPGmoDiYT+MWPSSn/Y3R8eiGPUqDdBUSaDdCafTWoU44yUzZhefAkEisT8sD9dzdECUQ1/F9Tqh4tAgMd6bpfJwh1vOhNpYcOGDDww0t1jHxvJJsYmJ+wStRE//wOnCwQdycQGxpdiSrxFv/EcHZuI0O5UE9B2TWNEL0cgX9jblF0+js6ZfCcdySv3Na8USu/SpOpu6uQ==
    mongo-root-username: AgA2odk5qY3XJKt4uYd16pO14ge/zgq/LnaSb/ScsOHW03qAsuJLXjKzfUIcibvW+Kd5G0RPfI/tL4QUPsiGQlfQAxCntLf4dNMwX+ZWMpg5zF9x8tnty9ebyw/zcRBUEI0s/pSUCRavb8sx9ki5Yjepvm7g5yvN4KCAXbDo8aqKnOPMprWW34CNhLEjRKP/iCtNZ36Q/Kp5nRMvKWxd120ilGBTjvEm+wiZlnPr/bHigwcTMG7eVO981VpkSZ5ZMWDkxn6IOOfZCwrmuL0Beso2xUQLQDcMeqQerQ62Reo6Ol8rkhqkST5+MLqJfOBi/S6NhwZHOR4BEpBo5KKaZeu6q4dLj5/ziEpVA9Jw5tD3lylvW/CUlrV8f2PhOKb6TXY51/oDMAVc8eWfbnNGAk2Qb1YuhKG03wkwWbHiQWNPJZnv3tLzsLD8MnVBbHTuECeiXPVzYjnUiSoNSBGO9U9oGZU/qBxv2uRSd7UxmcOqVdlk5DMw7sE6AmjYraN/QBUJX2uDsQXm++rz9QXwDmbu3euPbk14VIO9CHhMiviEq3m2N07TU3Val7chW7D9rv1XtDRT3p3bZ2dqzAHl3/FQC3NvcGFSQXbL8WzIu41gZb8poBuacqM4A4HuiUY2viKJI1VtJ+ynBzWb7oNT38/haG5JY/s1en+IovYn8F3xP7DoYLMgtL3XCa91YKqpddmNIaFVFRjO8A==
  template:
    metadata:
      creationTimestamp: null
      name: mongodb-secret
      namespace: mongo
    type: Opaque
